platform :ios, '13.0'

target 'RickAndMortyApp' do
  use_frameworks!

  # Pods for RickAndMortyApp
  pod 'Alamofire'

  target 'RickAndMortyAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RickAndMortyAppUITests' do
    # Pods for testing
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete('ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES')
      end
    end
  end
  

end

